name: Docker

# Trigger the workflow on push and pull request events
# to the main branch, as well as a scheduled cron job
on:
  schedule:
    - cron: '32 7 *'  # Run at 7:32 UTC every day
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io  # Use the GitHub Container Registry
  IMAGE_NAME: ${{ github.repository }}  # Image name is the repository name

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx to build multi-platform images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

    # Extract metadata for the Docker image
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # Build and push the Docker image for ARM64 architecture
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}  # Push only on push events, not PRs
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/arm64  # Build for ARM64 architecture (Raspberry Pi)
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Sign the published Docker image with cosign
    - name: Sign the published Docker image
      if: ${{ github.event_name != 'pull_request' }}  # Sign only on push events, not PRs
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
